apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mynginx
  labels:
    mynginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mynginx
  minReplicas: 1
  maxReplicas: 2
  metrics: 
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 30
